Repository UNOA-Project/UNOA-Back, pull requests merged in 2025-06, with the labels that each got.

#1 Feat: openai 연동 및 웹 소켓 연결
  .gitignore
  .prettierignore
  .prettierrc
  config/database.js
  config/db.js
  data/planDatabase.js
  eslint.config.js
  handlers/socketHandlers.js
  models/Conversation.js
  package-lock.json
  package.json
  routes/apiRoutes.js
  server.js
  utils/helpers.js
Labels: BUILD, FEAT

#3 Refactor: 요금제DB생성 및 prettier 수정
  .gitignore
  .prettierignore
  .prettierrc
  config/database.js
  config/prettierrc
  data/planDatabase.js
  eslint.config.js
  handlers/socketHandlers.js
  models/Conversation.js
  models/Plan.js
  package-lock.json
  package.json
  routes/apiRoutes.js
  scripts/seedDatabase.js
  server.js
  services/promptService.js
  utils/helpers.js
Labels: REFACTOR, BUILD

#4 Refactor: 프롬프트 수정 및 모델 변경
  config/prettierrc
  handlers/socketHandlers.js
  models/Conversation.js
  scripts/seedDatabase.js
  services/promptService.js
Labels: REFACTOR, CHORE, FEAT

#6 Feat: 로그인 기능
  config/jwt.js
  controllers/authController.js
  middlewares/authMiddleware.js
  routes/authRoutes.js
  server.js
Labels: BUILD, FEAT

#7 Feat: 요금제 추천카드 롤 추가 및 코드 리팩토링
  handlers/socketHandlers.js
  services/promptService.js
Labels: FEAT

#11 Feat: 마이페이지 혜택 데이터 MongoDB 저장 스크립트 추가
  scripts/seedBenefits.js
Labels: FEAT

#12 Feat: 카카오로그인 기능
  config/oauth.js
  controllers/kakaoAuthController.js
  middlewares/authMiddleware.js
  models/User.js
  package-lock.json
  package.json
  routes/kakaoAuthRoutes.js
  server.js
Labels: BUILD, FEAT

#16 Feat: 카카오 로그인 추가 정보 입력 로직 및 최종 가입 처리 기능 추가
  controllers/kakaoAuthController.js
  routes/kakaoAuthRoutes.js
Labels: FEAT

#19 Feat: 비밀번호 변경 API 추가
  controllers/authController.js
  routes/authRoutes.js
Labels: FEAT

#21 Refactor: 사용자 이름 기반 혜택 조회를 _id 기반으로 변경
  controllers/userController.js
  routes/userRoutes.js
Labels: REFACTOR

#23 Fix: 비교하기 최소화 및 모델 4.1-mini로 변경
  handlers/socketHandlers.js
  services/promptService.js
Labels: REFACTOR
